name: Deployment to Google Cloud Store

on:
  push:
    branches: 
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout/@v2

      - name: Authenticate Google Cloud SDK
        uses: google-github-actions/auth@v0.5.0
        with:
          service_account_key: ${{ SES_CE_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0
        with: 
          version: 'latest'
          project_id: neon-alcove-419010

      - name: Deploy to Google Cloud Storage
        run: gsutil -m rsync -r ./ gs://ses-ce
          
